### ISSUE TITLE
Rancher API Issues

### ISSUE THREAD

**Issue by ddelnano** [arkenio/arken#4]
I apologize in advance since this is not exactly a question about arken.  However, I will say I just watched the August 2016 Rancher meetup and the arken system is very awesome.  I hope to use it shortly :)

So to give some background I have been creating tools to work with the rancher api.  One pain point for me is that the github.com/rancher/go-rancher (which this project uses for the Rancher driver) seems to give you the ability to work with only certain operations.  For instance I am writing a custom cli for Rancher and I have found that when trying to create a stack through the api (Environment in api terms) I get the following error

```
Resource type [environment] is not creatable
```

In situations like this I just crafted the http request myself and off I went.  However, after I found out about arken I started looking at your source code since I was wondering if you guys also did the same thing that I just described.  But I was surprised to see [this](https://github.com/arkenio/arken/blob/master/goarken/drivers/rancher.go#L199) in the code.  I have tried this myself (the error message I showed).  So while I have not tried Arken I am assuming the code works since I watched the meetup and watched it in action.

So my questions are:
- Does that work with specific Rancher versions?  The validation that is preventing my request from working is feed by data that comes from `/v1/schemas` of Rancher's api.  I was not using the same git hash as you for go-rancher but I `git checkout`ed the version you are using and it seems to do the validation from the schemas from the api.

- Have you ran into the issue that I am describing??

Again I apologize that this is a non Arken issue.

**Comment by dmetzler** [comment]
Hello, it doesn't uses a specific rancher version, currently my demo was with 1.3 if I remember and I don't remember running into such issue. 
Feel free to ask your question on Rancher forum they are very responsive. I'm closing the issue.
